DSCF.Web.Main/Controllers/employeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DSCF.Model;
using DSCF.View;
using DSCF.Repository;

namespace DSCF.Web.Main.Controllers
{
    public class employeesController : Controller
    {
        private DSMainContext db = new DSMainContext();
        private EmployeeRepository emp = new EmployeeRepository();

        // GET: employees
        public ActionResult Index()
        {
            return View(emp.getAllEmployee());
        }
        public ActionResult ListEmployee()
        {
            return PartialView("_listEmployee", emp.getAllEmployee());
        }
        public ActionResult SearchEmployee(string keywords)
        {
            return PartialView("_listEmployee", emp.SearchListEmployee(keywords));
        }
        // GET: employees/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //EMPLOYEE eMPLOYEE = db.employees.Find(id);
            EmployeeViewModel employee = emp.getEmployee(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: employees/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmployeeViewModel employee)
        {
            if (ModelState.IsValid)
            {
                emp.SaveOrUpdate(employee);
                return RedirectToAction("Index");
            }

            return View(employee);
        }

        // GET: employees/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EMPLOYEE eMPLOYEE = db.employees.Find(id);
            if (eMPLOYEE == null)
            {
                return HttpNotFound();
            }
            return View(eMPLOYEE);
        }

        // POST: employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EmployeeViewModel employee)
        {
            if (ModelState.IsValid)
            {
                emp.SaveOrUpdate(employee);
            }
            return new EmptyResult();
        }

        // GET: employees/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EMPLOYEE eMPLOYEE = db.employees.Find(id);
            if (eMPLOYEE == null)
            {
                return HttpNotFound();
            }
            return View(eMPLOYEE);
        }

        // POST: employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            EMPLOYEE eMPLOYEE = db.employees.Find(id);
            eMPLOYEE.ACTIVE = false;
            //db.employees.Remove(eMPLOYEE);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DSCF.Web.Main/Views/employees/Create.cshtml
@model DSCF.View.EmployeeViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EMPLOYEE</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dept_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.dept_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dept_id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DSCF.Web.Main/Views/employees/Delete.cshtml
@model DSCF.Model.EMPLOYEE

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EMPLOYEE</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EMAIL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMAIL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DEPT_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DEPT_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ACTIVE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ACTIVE)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DSCF.Web.Main/Views/employees/Details.cshtml
@model DSCF.View.EmployeeViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>EMPLOYEE</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dept_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dept_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.active)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DSCF.Web.Main/Views/employees/Edit.cshtml
@model DSCF.Model.EMPLOYEE

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EMPLOYEE</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EMP_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.NAME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NAME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NAME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMAIL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMAIL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DEPT_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DEPT_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DEPT_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ACTIVE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ACTIVE)
                    @Html.ValidationMessageFor(model => model.ACTIVE, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DSCF.Web.Main/Views/employees/Index.cshtml
@model IEnumerable<DSCF.View.EmployeeViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<div class="card">
    <div class="card-body card-padding">
        <div class="col-sm-4">
            <div class="fg-line">
                <input type="text" class="form-control" id="search-item" placeholder="Search" />
            </div>
        </div>
        <div class="col-sm-offset-10">
            <p>
                <button id="btn-create" type="button" class="btn btn-primary btn-create">Create</button>
                @*@Html.ActionLink("Create New", "Create")*@
            </p>
        </div>


        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.dept_id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.active)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="tbl-employee"></tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript">
    $(document).ready(function () {
        listReload();

        $("#search-item").keyup(function () {
            var search = $(this).val();

            if ($(this).val() == "" || $(this).val() == null) {
                listReload();
            }
            else {
                $("#tbl-employee").html("");

                $.ajax({
                    type: "GET",
                    url: "@Url.Action("SearchEmployee", "employees")",
                    data: { keywords: search }, //data yang akan dikirim
                    dataType: "html",
                    success: function (data) {
                        $("#tbl-employee").html(data)
                    }
                });
            }
        });
    });

    function listReload() {
        $.ajax({
            url: "@Url.Action("ListEmployee", "employees")",
            type: "GET",
            success: function (result) {
                $("#tbl-employee").html(result);
            }
        });
    }
    $("#btn-create").click(function () {
        debugger;
        $.ajax({
            type: "GET",
            url: "@Url.Action("Create", "employees")",
            dataType: "html",
            success: function (data) {
                window.location.href = '/employees/Create'
            }
        });
    })

    
    
    </script>
}

DSCF.Web.Main/Views/employees/_listEmployee.cshtml
@model IEnumerable<DSCF.View.EmployeeViewModel>


@foreach (var item in Model) {
    <tr>
        <td class="emp_id">
            @Html.DisplayFor(modelItem => item.id)
        </td>
        <td class="emp_name">
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td class="emp_email">
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td class="dept_id">
            @Html.DisplayFor(modelItem => item.dept_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.active)
        </td>
        <td>
            @*<a class="Edit" href="javascript:;">Edit</a>*@
            <button type="button" class="btn btn-success btn-edit" edit dataid="@item.id">Edit</button>
            <button type="button" class="btn btn-info btn-detail" detail dataid="@item.id">Detail</button>
            <button type="button" class="btn btn-danger btn-delete" delete dataid="@item.id">Delete</button>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })*@
        </td>
    </tr>
}
<script type="text/javascript">
    $(".btn-edit").click(function () {
        debugger;
        var row = $(this).closest('tr');
        row.toggleClass('isediting'); // add a style to highlight the row
        var isediting = row.hasClass('isediting');
        $(this).parent('td').siblings('td').prop('contenteditable', isediting);
        if (isediting) {
            $(this).text('Ok');
            $(this).siblings().addClass("hidden");
            //$(this).siblings('button').find("btn-delete").addClass("hidden");
        } else {
            var employee = {};
            employee.id = row.find(".emp_id").text().replace(/\s+/g, '');
            employee.name = row.find(".emp_name").text().replace(/\s+/g, '');
            employee.email = row.find(".emp_email").text().replace(/\s+/g, '');
            employee.dept_id = row.find(".dept_id").text().replace(/\s+/g, '');

            $.ajax({
                type: "POST",
                url: "@Url.Action("Edit", "employees")",
                data: '{ employee:'+JSON.stringify(employee)+ '}',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
            });

            $(this).text('Edit');
            $(this).siblings().removeClass('hidden');
        }
    })
    $(".btn-detail").click(function () {
        debugger;
        var Id = $(this).attr("dataid");
        var idx = $(this).index();

        $.ajax({
            type: "GET",
            url: "@Url.Action("Details", "employees")",
            data: { id: Id }, //data yang akan dikirim
            dataType: "html",
            success: function (data) {
                window.location.href = '/employees/Details/'+Id
            }
        });
    })
    $(".btn-delete").click(function () {
        debugger;
        var Id = $(this).attr("dataid");
        $.ajax({
            type: "GET",
            url: "@Url.Action("Delete", "employees")",
            data: { id: Id }, //data yang akan dikirim
            dataType: "html",
            success: function (data) {
                window.location.href = '/employees/Delete/'+Id
            }
        });
    })
    function AppendRow(row, id, name, email, dept_id) {
        debugger;
        //Bind Id.
        $(".id", row).find("span").html(id);
        $(".id", row).find("input").val(id);

        //Bind Name.
        $(".name", row).find("span").html(name);
        $(".name", row).find("input").val(name);

        //Bind Email.
        $(".email", row).find("span").html(email);
        $(".email", row).find("input").val(email);

        //Bind Email.
        $(".dept_id", row).find("span").html(dept_id);
        $(".dept_id", row).find("input").val(dept_id);

        row.find(".Edit").show();
        row.find(".Delete").show();
        $("#tbl-employee").append(row);
    };
    $("body").on("click", "#tbl-employee .Edit", function () {
        debugger;
        var row = $(this).closest('tr');
        row.toggleClass('isediting'); // add a style to highlight the row
        var isediting = row.hasClass('isediting');
        $(this).parent('td').siblings('td').prop('contenteditable', isediting);
        if (isediting) {
            $(this).text('update');
        } else {
            $(this).text('edit');
        }
    });
</script>